apiVersion: v1
kind: Service
metadata:
  name: notes-service
  labels:
    app: notes-service
spec:
  selector:
    app: notes-service
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP