apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  annotations:
    linkerd.io/inject: enabled
    onfig.linkerd.io/proxy-await: "enabled"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: thsjowi/auth:1.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-password
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: redis-port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: redis-password
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: kafka-host
            - name: KAFKA_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: kafka-port
            - name: VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: vault-host
            - name: VAULT_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: vault-port
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: vault-token
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: MAILTRAP_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mailtrap-api-token
            - name: MAILTRAP_SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mailtrap-sender-email
            - name: MAILTRAP_SENDER_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mailtrap-sender-name

