apiVersion: v1
kind: Service
metadata:
  name: admin-server-nodeport
  labels:
    app: admin-server-nodeport
spec:
  selector:
    app: admin-server
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8090     
      targetPort: 8090 
      nodePort: 30090 