apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-service
  template:
    metadata:
      labels:
        app: notes-service
    spec:
      containers:
        - name: notes-service
          image: thsjowi/notes:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          
          env:
            - name: NOTES_SERVICE_PORT
              value: "8083"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-password
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: kafka-host
            - name: KAFKA_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: kafka-port
            - name: EUREKA_HOST
              value: "eureka-server"
            - name: EUREKA_PORT
              value: "8761"
            - name: AUTH_SERVICE_HOST
              value: "auth-service"
            - name: AUTH_SERVICE_PORT
              value: "8082"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret

---
apiVersion: v1
kind: Service
metadata:
  name: notes-service
  labels:
    app: notes-service
spec:
  selector:
    app: notes-service
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP