apiVersion: v1
kind: Service
metadata:
  name: gateway-service-nodeport
  labels:
    app: gateway-service-nodeport
spec:
  selector:
    app: gateway-service-nodeport
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8100     
      targetPort: 8100 
      nodePort: 30810 