apiVersion: v1
kind: Service
metadata:
  name: otp
  labels:
    app: otp
spec:
  selector:
    app: otp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8085
  type: ClusterIP
