apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  ingressClassName: public
  rules:
  - http:
      paths:
      - path: /api/v1/auth
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 80
  - http:
      paths:
      - path: /api/v1/notes
        pathType: Prefix
        backend:
          service:
            name: notes
            port:
              number: 80
  - http:
     paths:
     - path: /api/v1/passwords
       pathType: Prefix
       backend:
         service:
           name: password
           port:
             number: 80
  - http:
     paths:
     - path: /api/v1/otp
       pathType: Prefix
       backend:
         service:
           name: otp
           port:
             number: 80
  - http:
     paths:
     - path: /cockroachdb
       pathType: Prefix
       backend:
         service:
           name: cockroachdb
           port:
             number: 80
  
