apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Database
  db-port: "YOUR_DB_PORT"
  db-username: "YOUR_DB_USERNAME"
  db-password: "YOUR_DB_PASSWORD"
  
  # Redis/KeyDB
  redis-port: "6379"
  redis-password: "" 
  # Kafka
  kafka-host: kafka-bootstrap
  kafka-port: "9092"
  
  # Vault
  vault-host: "YOUR_VAULT_IP"
  vault-port: "8200"
  vault-token: "YOUR_VAULT_TOKEN"
  
  # JWT
  jwt-secret: "YOUR_JWT_SECRET_KEY"
