apiVersion: v1
kind: Service
metadata:
  name: keydb
  labels:
    app: keydb
spec:
  type: ClusterIP
  selector:
    app: keydb
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  sessionAffinity: None
