server:
  port: 8100
  address: 0.0.0.0

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      routes:
        - id: auth-service-api
          uri: http://auth-service:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
            - AddResponseHeader=X-Service-Name, auth-service

        - id: notes-service-api
          uri: http://notes-service:8083
          predicates:
            - Path=/api/v1/notes/**
          filters:
            - StripPrefix=0
            - AddResponseHeader=X-Service-Name, notes-service

        - id: password-service
          uri: http://password-service:8084
          predicates:
            - Path=/api/v1/passwords/**
          filters:
            - StripPrefix=0
            - AddResponseHeader=X-Service-Name, password-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
