apiVersion: v1
kind: Service
metadata:
  name: discovery-nodeport
  labels:
    app: discovery-nodeport
spec:
  selector:
    app: discovery
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8761     
      targetPort: 8761 
      nodePort: 30876 