server:
  port: ${EUREKA_PORT:8761}
  # Allow connections from any network interface (not just localhost)
  address: 0.0.0.0

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:eureka-server}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:${EUREKA_PORT:8761}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false