apiVersion: v1
kind: Service
metadata:
  name: notes
  labels:
    app: notes
spec:
  selector:
    app: notes
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP