apiVersion: v1
kind: Service
metadata:
  name: password
  labels:
    app: password
spec:
  selector:
    app: password
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP