apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-nodeport
  labels:
    app: cockroachdb-nodeport
spec:
  selector:
    app: cockroachdb-nodeport
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080     
      targetPort: 8080 
      nodePort: 30080 