piVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - name: http
      protocol: TCP
      port: 8761         # port within the cluster
      targetPort: 8761    # container port
  type: ClusterIP
