apiVersion: v1
kind: Service
metadata:
  name: api-gateway-nodeport
  labels:
    app: api-gateway-nodeport
spec:
  selector:
    app: api-gateway
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8100     
      targetPort: 8100 
      nodePort: 30810 